version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  rails: finalcad/rails@2.1.0
  bundle-install: toshimaru/bundle-install@0.3.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - run: 
         name: Checkout
         command: checkout
      - run:
         name: Bundle Inatall
         command: ruby/bundle-install
      - run:
          name: Which bundler?
          command: bundle -v
      - run: pwd
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec
