version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  bundle-install: toshimaru/bundle-install@0.3.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
